const ENDPOINTS = {
  CATEGORIES: {
    GET_ALL: `/categories`,
    GET_ONE: (id: string) => `/categories/${id}`,
    CREATE: `/categories/create`,
    UPDATE: (id: string) => `/categories/update/${id}`,
    DELETE: (id: string) => `/categories/delete/${id}`,
  },
  VARIANT: {
    GET_ALL: `/variants`,
    GET_ONE: (id: string) => `/variants/${id}`,
    CREATE: `/variants`,
    UPDATE: (id: string) => `/variants/${id}`,
    DELETE: (id: string) => `/variants/${id}`,
  },
  VARIANT_VALUE: {
    GET_ALL: `/variant-values`,
    GET_ONE: (id: string) => `/variant-values/${id}`,
    CREATE: `/variant-values`,
    UPDATE: (id: string) => `/variant-values/${id}`,
    DELETE: (id: string) => `/variant-values/${id}`,
  },
  ROLE: {
    GET_ALL: `/roles`,
    GET_ONE: (id: string) => `/roles/${id}`,
    CREATE: `/roles`,
    UPDATE: (id: string) => `/roles/${id}`,
    DELETE: (id: string) => `/roles/${id}`,
  },
  AUTH: {
    LOGIN: `/auth/login`,
    REGISTER: `/auth/register`,
    REFRESH_TOKEN: `/auth/refresh`,
    LOGOUT: `/auth/logout`,
  },
  USER: {
    GET_ALL: `/users`,
    GET_ONE: (id: string) => `/users/${id}`,
    CREATE: `/users`,
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
    PROFILE: `/user/profile`,
    UPDATE_PROFILE: `/user/update`,
    DELETE_ACCOUNT: `/user/delete`,
  },
  POSTS: {
    GET_ALL: `/posts`,
    GET_ONE: (id: string) => `/posts/${id}`,
    CREATE: `/posts/create`,
    UPDATE: (id: string) => `/posts/update/${id}`,
    DELETE: (id: string) => `/posts/delete/${id}`,
  },
  PRODUCT: {
    GET_ALL: `/products`,
    GET_ONE: (id: string) => `/products/${id}`,
    CREATE: `/products`,
    UPDATE: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
  },
  CONSIGNMENT: {
    GET_ALL: `/consignments`,
    GET_ONE: (id: string) => `/consignments/${id}`,
    CREATE: `/consignments`,
    UPDATE: (id: string) => `/consignments/${id}`,
    DELETE: (id: string) => `/consignments/${id}`,
  },
  SUPPLIER: {
    GET_ALL: `/suppliers`,
    GET_ONE: (id: string) => `/suppliers/${id}`,
    CREATE: `/suppliers`,
    UPDATE: (id: string) => `/suppliers/${id}`,
    DELETE: (id: string) => `/suppliers/${id}`,
  },
  CUSTOMER: {
    GET_ALL: `/customers`,
    GET_ONE: (id: string) => `/customers/${id}`,
    CREATE: `/customers`,
    UPDATE: (id: string) => `/customers/${id}`,
    DELETE: (id: string) => `/customers/${id}`,
  },
};
export default ENDPOINTS;
