const ENDPOINTS = {
  CATEGORIES: {
    GET_ALL: `/categories`,
    GET_ONE: (id: string) => `/categories/${id}`,
    CREATE: `/categories`,
    UPDATE: (id: string) => `/categories/${id}`,
    DELETE: (id: string) => `/categories/${id}`,
  },
  VARIANT: {
    GET_ALL: `/variants`,
    GET_ONE: (id: string) => `/variants/${id}`,
    CREATE: `/variants`,
    UPDATE: (id: string) => `/variants/${id}`,
    DELETE: (id: string) => `/variants/${id}`,
  },
  VARIANT_VALUE: {
    GET_ALL: `/variant-values`,
    GET_ONE: (id: string) => `/variant-values/${id}`,
    CREATE: `/variant-values`,
    UPDATE: (id: string) => `/variant-values/${id}`,
    DELETE: (id: string) => `/variant-values/${id}`,
  },
  ROLE: {
    GET_ALL: `/roles`,
    GET_ONE: (id: string) => `/roles/${id}`,
    CREATE: `/roles`,
    UPDATE: (id: string) => `/roles/${id}`,
    DELETE: (id: string) => `/roles/${id}`,
  },
  AUTH: {
    LOGIN: (username: string, password: string) =>
      `/auth/login?username=${username}&password=${password}`,
    REGISTER: `/auth/register`,
    REFRESH_TOKEN: `/auth/refresh`,
    LOGOUT: `/auth/logout`,
  },
  USER: {
    GET_ALL: `/users`,
    GET_ONE: (id: string) => `/users/${id}`,
    CREATE: `/users`,
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
    PROFILE: `/user/profile`,
    UPDATE_PROFILE: `/user/update`,
    DELETE_ACCOUNT: `/user/delete`,
  },
  POSTS: {
    GET_ALL: `/posts`,
    GET_ONE: (id: string) => `/posts/${id}`,
    CREATE: `/posts/create`,
    UPDATE: (id: string) => `/posts/update/${id}`,
    DELETE: (id: string) => `/posts/delete/${id}`,
  },
  PRODUCT: {
    GET_ALL: `/products`,
    GET_ONE: (id: string) => `/products/${id}`,
    CREATE: `/products`,
    UPDATE: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
  },
  CONSIGNMENT: {
    GET_ALL: `/consignments`,
    GET_ONE: (id: string) => `/consignments/${id}`,
    CREATE: `/consignments`,
    UPDATE: (id: string) => `/consignments/${id}`,
    DELETE: (id: string) => `/consignments/${id}`,
  },
  SUPPLIER: {
    GET_ALL: `/suppliers`,
    GET_ONE: (id: string) => `/suppliers/${id}`,
    CREATE: `/suppliers`,
    UPDATE: (id: string) => `/suppliers/${id}`,
    DELETE: (id: string) => `/suppliers/${id}`,
  },
  CUSTOMER: {
    GET_ALL: `/customers`,
    GET_ONE: (id: string) => `/customers/${id}`,
    CREATE: `/customers`,
    UPDATE: (id: string) => `/customers/${id}`,
    DELETE: (id: string) => `/customers/${id}`,
  },
  PURCHASE_ORDERS: {
    GET_ALL: `/purchase-orders`,
    GET_ONE: (id: string) => `/purchase-orders/${id}`,
    CREATE: `/purchase-orders`,
    UPDATE: (id: string) => `/purchase-orders/${id}`,
    DELETE: (id: string) => `/purchase-orders/${id}`,
  },
  ORDER: {
    GET_ALL: `/orders`,
    GET_ONE: (id: string) => `/orders/${id}`,
    CREATE: `/orders`,
    UPDATE: (id: string) => `/orders/${id}`,
    DELETE: (id: string) => `/orders/${id}`,
  },
  ORDER_DETAIL: {
    GET_ALL: `/order-details`,
    GET_ONE: (id: string) => `/order-details/${id}`,
    CREATE: (orderGuid: string) => `/order-details/${orderGuid}`,
    UPDATE: (id: string) => `/order-details/${id}`,
    DELETE: (id: string) => `/order-details/${id}`,
  },
  LOCATION: {
    GET_ALL: `/locations`,
    GET_ONE: (id: string) => `/locations/${id}`,
    CREATE: `/locations`,
    UPDATE: (id: string) => `/locations/${id}`,
    DELETE: (id: string) => `/locations/${id}`,
  },
  INVENTORY: {
    GET_ALL: `/inventories`,
    GET_ONE: (id: string) => `/inventories/${id}`,
    CREATE: `/inventories`,
    UPDATE: (id: string) => `/inventories/${id}`,
    DELETE: (id: string) => `/inventories/${id}`,
  },
  TRANSFER_REQUESTS: {
    GET_ALL: `/transfer-requests`,
    GET_ONE: (id: string) => `/transfer-requests/${id}`,
    CREATE: `/transfer-requests`,
    UPDATE: (id: string) => `/transfer-requests/${id}`,
    DELETE: (id: string) => `/transfer-requests/${id}`,
  },
  TRANSACTION: {
    GET_ALL: `/transactions`,
    GET_ONE: (id: string) => `/transactions/${id}`,
    CREATE: `/transactions`,
    UPDATE: (id: string) => `/transactions/${id}`,
    DELETE: (id: string) => `/transactions/${id}`,
  },
};
export default ENDPOINTS;
